### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [Waller-SUSAN/envi#3]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by idblr** [comment]
Thanks, @rsbivand. I'll get this sorted asap.

**Comment by idblr** [comment]
@rsbivand I have a new branch [dev_rspatial_depends](https://github.com/lance-waller-lab/envi/tree/dev_rspatial_depends) with the R-spatial package migration. It's passing checks, but please let me know if it was successful. 

`maptools` was in Suggests because it's used in an example in the vignette to convert an object of class `RasterLayer` to `im`. I designed a crude replacement with a new internal function to convert an object of class `SpatRaster` to `im`. I hope this stopgap is temporary and this conversion will be possible in `terra` or the `spatstat` suite.

Also, an example in the vignette uses the `RStoolbox` package (in Suggests) that currently depends on `raster` so `envi` can fully migrate once `RStoolbox` does.

**Comment by rsbivand** [comment]
[00check.log](https://github.com/lance-waller-lab/envi/files/10253823/00check.log) for R_LIBS=/home/rsb/lib/r_libs R CMD check --as-cran envi_0.1.16.9000.tar.gz built from the [dev_rspatial_depends](https://github.com/lance-waller-lab/envi/tree/dev_rspatial_depends) branch. Thanks! See also 
https://github.com/r-spatial/evolution/issues/8.

**Comment by idblr** [comment]
Thanks, @rsbivand!
